FROM openjdk:8-jdk-alpine

COPY ./target/SpringBootWithH2-0.0.1-SNAPSHOT.jar /usr/app/

WORKDIR /usr/app

RUN sh -c 'touch SpringBootWithH2-0.0.1-SNAPSHOT.jar'

ENTRYPOINT ["java","-jar","SpringBootWithH2-0.0.1-SNAPSHOT.jar"]